import { FaDollarSign } from 'react-icons/fa';
import type { BlockDefinition } from '../registry/types';

export const pricingPlansBlock: BlockDefinition = {
  type: 'pricing-plans',
  name: 'Fiyatlandırma',
  category: 'corporate',
  icon: FaDollarSign,
  defaultProps: {
    title: 'Paketler & Fiyatlar',
    subtitle: 'İhtiyacınıza en uygun planı seçin. Tüm planlar 30 gün ücretsiz deneme içerir.',
    showAnnualToggle: true,
    annualDiscountText: '%20 tasarruf et',
    plans: [
      {
        name: 'Başlangıç',
        price: '2.990',
        priceAnnual: '2.392',
        currency: '₺',
        period: '/ay',
        description: 'Küçük ekipler ve girişimler için ideal başlangıç noktası.',
        highlighted: false,
        badge: '',
        buttonText: 'Ücretsiz Dene',
        buttonLink: '/kayit?plan=starter',
        features: [
          { text: '5 kullanıcıya kadar',         included: true  },
          { text: '10 GB depolama alanı',         included: true  },
          { text: 'Temel raporlama',              included: true  },
          { text: 'E-posta desteği',              included: true  },
          { text: 'API erişimi (1.000 istek/gün)', included: false },
          { text: 'Özel entegrasyonlar',          included: false },
          { text: 'Öncelikli destek',             included: false },
          { text: 'SLA garantisi',                included: false },
        ],
      },
      {
        name: 'Profesyonel',
        price: '7.990',
        priceAnnual: '6.392',
        currency: '₺',
        period: '/ay',
        description: 'Büyüyen işletmeler için gelişmiş özellikler ve esneklik.',
        highlighted: true,
        badge: 'En Popüler',
        buttonText: 'Hemen Başla',
        buttonLink: '/kayit?plan=pro',
        features: [
          { text: '25 kullanıcıya kadar',          included: true },
          { text: '100 GB depolama alanı',         included: true },
          { text: 'Gelişmiş raporlama & analitik', included: true },
          { text: 'Öncelikli e-posta & sohbet desteği', included: true },
          { text: 'API erişimi (50.000 istek/gün)', included: true },
          { text: '10 özel entegrasyon',           included: true },
          { text: 'Öncelikli destek',              included: true },
          { text: 'SLA garantisi',                 included: false },
        ],
      },
      {
        name: 'Kurumsal',
        price: 'Teklif Alın',
        priceAnnual: 'Teklif Alın',
        currency: '',
        period: '',
        description: 'Büyük kuruluşlar için özelleştirilebilir, ölçeklenebilir çözümler.',
        highlighted: false,
        badge: 'Özel Fiyatlandırma',
        buttonText: 'Bize Ulaşın',
        buttonLink: '/iletisim?plan=enterprise',
        features: [
          { text: 'Sınırsız kullanıcı',                  included: true },
          { text: 'Sınırsız depolama alanı',             included: true },
          { text: 'Özel raporlama & BI entegrasyonu',    included: true },
          { text: '7/24 telefon & e-posta desteği',      included: true },
          { text: 'Sınırsız API erişimi',                included: true },
          { text: 'Sınırsız özel entegrasyon',           included: true },
          { text: 'Dedicated hesap yöneticisi',          included: true },
          { text: '%99.9 uptime SLA garantisi',          included: true },
        ],
      },
    ],
  },
  propsSchema: [
    { field: 'title',              type: 'text',    label: 'Başlık',              group: 'content'  },
    { field: 'subtitle',           type: 'textarea', label: 'Alt Başlık', rows: 2, group: 'content'  },
    { field: 'showAnnualToggle',   type: 'boolean', label: 'Yıllık/Aylık Geçiş', group: 'advanced' },
    { field: 'annualDiscountText', type: 'text',    label: 'İndirim Etiketi',     group: 'content'  },
    {
      field: 'plans', type: 'json-array', label: 'Paketler', group: 'content',
      itemSchema: [
        { key: 'name',        label: 'Paket Adı',     type: 'text'     },
        { key: 'price',       label: 'Aylık Fiyat',   type: 'text'     },
        { key: 'priceAnnual', label: 'Yıllık Fiyat',  type: 'text'     },
        { key: 'currency',    label: 'Para Birimi',   type: 'text'     },
        { key: 'description', label: 'Açıklama',      type: 'textarea' },
        { key: 'badge',       label: 'Rozet',         type: 'text'     },
        { key: 'buttonText',  label: 'Buton Metni',   type: 'text'     },
        { key: 'buttonLink',  label: 'Buton Linki',   type: 'url'      },
      ],
    },
  ],
  children: [
    { key: 'title',    label: 'Başlık',    selector: 'h2' },
    { key: 'subtitle', label: 'Alt Başlık', selector: 'p'  },
    { key: 'plans',    label: 'Paketler',  selector: 'ul' },
  ],
  toCss: (_props, theme) => {
    return [
      `.pricing-plans h2 { color: ${theme.colors.text}; font-family: ${theme.typography.fontFamily}; font-weight: ${theme.typography.headingWeight}; }`,
      `.pricing-plans .pricing-subtitle { color: ${theme.colors.textMuted}; }`,
      `.pricing-plans .plan-card { background: ${theme.colors.surface}; border-radius: ${theme.borderRadius.card}; border: 2px solid ${theme.colors.border}; transition: border-color 0.2s; }`,
      `.pricing-plans .plan-card.highlighted { border-color: ${theme.colors.primary}; box-shadow: 0 0 0 4px ${theme.colors.primary}22; }`,
      `.pricing-plans .plan-name { color: ${theme.colors.text}; font-weight: ${theme.typography.headingWeight}; }`,
      `.pricing-plans .plan-price { color: ${theme.colors.primary}; font-size: 2.5rem; font-weight: 700; }`,
      `.pricing-plans .plan-badge { background: ${theme.colors.primary}; color: #fff; border-radius: ${theme.borderRadius.md}; font-size: 0.75rem; font-weight: 600; }`,
      `.pricing-plans .feature-item.included { color: ${theme.colors.text}; }`,
      `.pricing-plans .feature-item.excluded { color: ${theme.colors.textMuted}; text-decoration: line-through; opacity: 0.5; }`,
      `.pricing-plans .plan-btn { background: ${theme.colors.primary}; color: #fff; border-radius: ${theme.borderRadius.button}; font-weight: 600; }`,
      `.pricing-plans .toggle-btn.active { background: ${theme.colors.primary}; color: #fff; }`,
    ].join('\n');
  },
};
